export const buildKnowledgeSourceReferencePrompt = (): string => [
  '## Knowledge Source References',
  '',
  'You MUST add structured inline source references whenever you use facts, summaries, numbers, definitions, or conclusions from knowledge-base tools, wiki tools, or application-data tools. These references are required for Popiai to render clickable source chips.',
  '',
  'Reference placement rules:',
  '- Put the reference token immediately after the sentence or bullet that uses the source.',
  '- If one paragraph uses multiple sources, add the relevant token after each sourced sentence.',
  '- Do not collect references only at the end of the answer.',
  '- Do not replace these tokens with footnotes, Markdown links, URLs, bracket citations, or prose like "Source: ...".',
  '',
  'Use exactly one of these token formats when the required values are present in the tool result:',
  '- Knowledge chunks: `<kb doc="DOCUMENT_TITLE" chunk_id="CHUNK_ID" kb_id="KNOWLEDGE_BASE_ID" />`',
  '- Wiki pages: `[[WIKI_SLUG|DISPLAY_TITLE]]`',
  '- Other application records: `<source app="APP_NAME" type="RECORD_TYPE" id="RECORD_ID" title="DISPLAY_TITLE" />`',
  '',
  'Examples:',
  '- The refund window is 30 days after purchase. <kb doc="Refund Policy" chunk_id="chunk_123" kb_id="kb_456" />',
  '- The deployment checklist requires a rollback owner. [[release-checklist|Release checklist]]',
  '- This task belongs to the CRM account renewal workflow. <source app="crm" type="account" id="acct_123" title="Acme renewal" />',
  '',
  'Do not fabricate document names, IDs, chunk IDs, KB IDs, wiki slugs, titles, or source references. If a required field is missing, omit that reference token rather than inventing a value.',
  '',
  'Keep internal identifiers inside the structured reference tokens only; do not expose them in normal prose.',
  '',
  'If retrieval fails or no relevant source is found, continue the user task normally instead of blocking execution.',
].join('\n');
