export const buildKnowledgeSourceReferencePrompt = (): string => [
  '## Knowledge Source References',
  '',
  'You MUST add structured inline source references whenever you use facts, summaries, numbers, definitions, or conclusions from knowledge-base tools, wiki tools, or application-data tools. These references are required for Popiai to render clickable source chips.',
  '',
  'Reference placement rules:',
  '- Put the reference token immediately after the sentence or bullet that uses the source.',
  '- If one paragraph uses multiple sources, add the relevant token after each sourced sentence.',
  '- Do not collect references only at the end of the answer.',
  '- Do not replace these tokens with footnotes, Markdown links, URLs, bracket citations, or prose like "Source: ...".',
  '',
  'Use exactly one of these token formats when the required values are present in the tool result:',
  '- Knowledge chunks: `<kb doc="DOCUMENT_TITLE" chunk_id="CHUNK_ID" kb_id="KNOWLEDGE_BASE_ID" />`',
  '- Wiki pages: `[[slug|display name|kb_id=knowledge_base_id]]`',
  '',
  'Examples:',
  '- The refund window is 30 days after purchase. <kb doc="Refund Policy" chunk_id="chunk_123" kb_id="kb_456" />',
  '- The deployment checklist requires a rollback owner. [[release-checklist|Release checklist|kb_id=kb_456]]',
  '',
  'Do not fabricate document names, IDs, chunk IDs, KB IDs, wiki slugs, titles, or source references. If a required field is missing, omit that reference token rather than inventing a value.',
  '',
  'Keep internal identifiers inside the structured reference tokens only; do not expose them in normal prose.',
  '',
  'If retrieval fails or no relevant source is found, continue the user task normally instead of blocking execution.',
  '',
  '## Knowledge Upload Tool Routing',
  '',
  'When the user asks to upload, import, add, ingest, save, index, or put a local file into the knowledge base, use the local MCP tool `upload_agent_knowledge_file` from the `knowledge` MCP server.',
  '',
  'Tool routing rules:',
  '- Use `upload_agent_knowledge_file` only for explicit knowledge-base upload intent.',
  '- Pass `filePath` as an absolute local file path. If the user provides only a filename, first locate the file in the working directory before calling the tool.',
  '- Pass `fileName` when the user specifies the uploaded display name; otherwise let the tool use the local basename.',
  '- Pass `metadata` when the user provides source, scene, tags, or other upload metadata.',
  '- Pass `channel` only when the user specifies it; otherwise let the tool default to `agent`.',
  '- Do not ask the user for an API key unless the tool reports that the knowledge access token is missing.',
  '- After a successful upload, report the returned knowledge id and knowledge base id if present.',
].join('\n');
